import json
import uuid
import os
import asyncio
import asyncpg
import tempfile
from datetime import datetime, timezone
from dotenv import load_dotenv, find_dotenv
from langchain_core.tools import tool
from pydantic import BaseModel, Field

# New import for pure-Python PDF generation
from xhtml2pdf import pisa
from supabase import create_client, Client

load_dotenv(find_dotenv())
DATABASE_URL = os.getenv("POSTGRES_URL")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

class GenerateReportInput(BaseModel):
    start_date: str = Field(..., description="The start date of the reporting period.")
    end_date: str = Field(..., description="The end date of the reporting period.")
    total_energy_kwh: float = Field(..., description="Total energy consumed in kWh.")
    carbon_emissions_kg: float = Field(..., description="Total estimated carbon emissions in kg.")
    hvac_efficiency: int = Field(..., description="The average HVAC system efficiency score.")
    requested_by: str = Field("System Admin", description="The admin user requesting the report.")


def generate_and_upload_pdf(report_data: dict) -> str:
    """
    Synchronous helper function to generate the PDF using xhtml2pdf 
    and upload it to Supabase.
    """
    report_id = report_data["id"]
    
    # 1. Draft the HTML content (Adjusted for xhtml2pdf compatibility)
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @page {{
                size: a4;
                margin: 2cm;
            }}
            body {{ font-family: Helvetica, sans-serif; color: #333333; line-height: 1.5; }}
            .header {{ text-align: center; border-bottom: 1px solid #2E7D32; padding-bottom: 10px; margin-bottom: 20px; }}
            h1 {{ color: #2E7D32; font-size: 24px; }}
            h2 {{ color: #1565C0; font-size: 18px; margin-top: 20px; padding-bottom: 5px; border-bottom: 1px solid #eeeeee; }}
            .metadata {{ font-size: 12px; color: #555555; margin-bottom: 20px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ border: 1px solid #dddddd; padding: 8px; text-align: left; font-size: 14px; }}
            th {{ background-color: #f0f4f8; font-weight: bold; }}
            .insight-box {{ background-color: #e3f2fd; padding: 15px; margin-top: 15px; font-size: 14px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Official ESG Performance Report</h1>
        </div>
        
        <div class="metadata">
            <strong>Report ID:</strong> {report_id}<br/>
            <strong>Reporting Period:</strong> {report_data['start_date']} to {report_data['end_date']}<br/>
            <strong>Generated By:</strong> {report_data['requested_by']}<br/>
            <strong>Date Generated:</strong> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
        </div>
        
        <h2>1. Executive Summary</h2>
        <p>This report provides a comprehensive overview of the facility's Environmental, Social, and Governance (ESG) performance for the specified period. The primary focus of this assessment is on energy consumption, carbon footprint tracking, and HVAC operational efficiency.</p>
        
        <h2>2. Key ESG Indicators Summary</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Recorded Value</th>
            </tr>
            <tr>
                <td>Total Energy Consumed</td>
                <td>{report_data['total_energy_kwh']:,.2f} kWh</td>
            </tr>
            <tr>
                <td>Estimated Carbon Emissions</td>
                <td>{report_data['carbon_emissions_kg']:,.2f} kg CO2e</td>
            </tr>
            <tr>
                <td>HVAC Efficiency Rating</td>
                <td>{report_data['hvac_efficiency']}%</td>
            </tr>
            <tr>
                <td>Overall Sustainability Status</td>
                <td><strong>{report_data['sustainability_status']}</strong></td>
            </tr>
        </table>
        
        <h2>3. Environmental Insights & Recommendations</h2>
        <p>During the reporting period, the monitored facility consumed <strong>{report_data['total_energy_kwh']:,.2f} kWh</strong> of total energy. Based on regional grid emissions factors, this correlates to a carbon footprint of <strong>{report_data['carbon_emissions_kg']:,.2f} kg CO2e</strong>.</p>
        
        <div class="insight-box">
            <strong>HVAC Performance Insight:</strong><br/>
            The HVAC systems operated at an average efficiency rating of {report_data['hvac_efficiency']}%. 
            {
                "This indicates highly optimal performance. Continued preventative maintenance is advised to maintain these levels." 
                if report_data['hvac_efficiency'] >= 90 
                else "This indicates a decline in expected performance. Immediate optimization, filter replacement, or system auditing is recommended to reduce energy waste."
            }
        </div>
    </body>
    </html>
    """

    # 2. Convert HTML to PDF safely across Windows/Mac/Linux
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, f"{report_id}.pdf")
    
    with open(pdf_path, "w+b") as result_file:
        pisa_status = pisa.CreatePDF(html_content, dest=result_file)
        
    if pisa_status.err:
        raise Exception("xhtml2pdf failed to generate the PDF.")

    # 3. Upload to Supabase Storage
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    file_name = f"{report_id}.pdf"
    bucket_name = "esg-reports" 

    with open(pdf_path, 'rb') as f:
        supabase.storage.from_(bucket_name).upload(
            path=file_name,
            file=f,
            file_options={"content-type": "application/pdf"}
        )

    # 4. Get Public URL and clean up local file
    public_url = supabase.storage.from_(bucket_name).get_public_url(file_name)
    os.remove(pdf_path)
    
    return public_url


@tool(args_schema=GenerateReportInput)
async def generate_esg_report_tool(start_date: str, end_date: str, total_energy_kwh: float, carbon_emissions_kg: float, hvac_efficiency: int, requested_by: str = "System Admin") -> str:
    """
    Creates an ESG report, generates a formatted PDF, uploads it to Supabase Storage, 
    and saves the final record with the PDF link into the database.
    """
    try:
        start_dt = datetime.fromisoformat(start_date.replace("Z", "+00:00"))
        end_dt = datetime.fromisoformat(end_date.replace("Z", "+00:00"))
    except ValueError:
        return "ERROR: Invalid date format. Please use ISO 8601. DO NOT RETRY."

    if not DATABASE_URL or not SUPABASE_URL:
        return "CRITICAL ERROR: Database or Supabase URL is not configured. DO NOT RETRY."

    try:
        report_id = f"ESG-{datetime.now(timezone.utc).strftime('%Y%m')}-{str(uuid.uuid4())[:6].upper()}"
        sustainability_status = "Optimal" if hvac_efficiency >= 90 else "Requires Optimization"
        
        # 1. Generate PDF and Upload to Storage
        report_data_for_pdf = {
            "id": report_id,
            "start_date": start_date,
            "end_date": end_date,
            "requested_by": requested_by,
            "total_energy_kwh": total_energy_kwh,
            "carbon_emissions_kg": carbon_emissions_kg,
            "hvac_efficiency": hvac_efficiency,
            "sustainability_status": sustainability_status
        }
        
        pdf_url = await asyncio.to_thread(generate_and_upload_pdf, report_data_for_pdf)

        # 2. Save record to PostgreSQL database
        conn = await asyncpg.connect(DATABASE_URL)
        try:
            query = """
                INSERT INTO esg_reports (
                    id, period_start, period_end, generated_by, 
                    total_energy_kwh, carbon_footprint_kg, 
                    hvac_efficiency_rating, sustainability_status, report_pdf_url
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
            """
            await conn.execute(
                query,
                report_id,
                start_dt,
                end_dt,
                requested_by,
                total_energy_kwh,
                carbon_emissions_kg,
                hvac_efficiency,
                sustainability_status,
                pdf_url
            )
        finally:
            await conn.close()
        
        return json.dumps({
            "status": "success",
            "message": "Successfully generated ESG Report, created PDF, and saved to database.",
            "report_id": report_id,
            "pdf_download_url": pdf_url,
            "summary": {
                "id": report_id,
                "period_start": start_date,
                "period_end": end_date,
                "generated_by": requested_by,
                "total_energy_kwh": total_energy_kwh,
                "carbon_footprint_kg": carbon_emissions_kg,
                "hvac_efficiency_rating": hvac_efficiency,
                "sustainability_status": sustainability_status,
                "report_pdf_url": pdf_url
            }
        })
        
    except Exception as e:
        return f"CRITICAL ERROR - Failed to generate ESG report: {str(e)}. DO NOT RETRY."