# import json
# import uuid
# import os
# import asyncio
# import asyncpg
# import tempfile
# from datetime import datetime, timezone
# from dotenv import load_dotenv, find_dotenv
# from langchain_core.tools import tool
# from pydantic import BaseModel, Field

# # New import for pure-Python PDF generation
# from xhtml2pdf import pisa
# from supabase import create_client, Client

# load_dotenv(find_dotenv())
# DATABASE_URL = os.getenv("POSTGRES_URL")
# SUPABASE_URL = os.getenv("SUPABASE_URL")
# SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY")

# class GenerateReportInput(BaseModel):
#     start_date: str = Field(..., description="The start date of the reporting period.")
#     end_date: str = Field(..., description="The end date of the reporting period.")
#     total_energy_kwh: float = Field(..., description="Total energy consumed in kWh.")
#     carbon_emissions_kg: float = Field(..., description="Total estimated carbon emissions in kg.")
#     hvac_efficiency: int = Field(..., description="The average HVAC system efficiency score.")
#     requested_by: str = Field("System Admin", description="The admin user requesting the report.")


# def generate_and_upload_pdf(report_data: dict) -> str:
#     """
#     Synchronous helper function to generate the PDF using xhtml2pdf 
#     and upload it to Supabase.
#     """
#     report_id = report_data["id"]
    
#     # 1. Draft the HTML content (Adjusted for xhtml2pdf compatibility)
#     html_content = f"""
#     <!DOCTYPE html>
#     <html>
#     <head>
#         <style>
#             @page {{
#                 size: a4;
#                 margin: 2cm;
#             }}
#             body {{ font-family: Helvetica, sans-serif; color: #333333; line-height: 1.5; }}
#             .header {{ text-align: center; border-bottom: 1px solid #2E7D32; padding-bottom: 10px; margin-bottom: 20px; }}
#             h1 {{ color: #2E7D32; font-size: 24px; }}
#             h2 {{ color: #1565C0; font-size: 18px; margin-top: 20px; padding-bottom: 5px; border-bottom: 1px solid #eeeeee; }}
#             .metadata {{ font-size: 12px; color: #555555; margin-bottom: 20px; }}
#             table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
#             th, td {{ border: 1px solid #dddddd; padding: 8px; text-align: left; font-size: 14px; }}
#             th {{ background-color: #f0f4f8; font-weight: bold; }}
#             .insight-box {{ background-color: #e3f2fd; padding: 15px; margin-top: 15px; font-size: 14px; }}
#         </style>
#     </head>
#     <body>
#         <div class="header">
#             <h1>Official ESG Performance Report</h1>
#         </div>
        
#         <div class="metadata">
#             <strong>Report ID:</strong> {report_id}<br/>
#             <strong>Reporting Period:</strong> {report_data['start_date']} to {report_data['end_date']}<br/>
#             <strong>Generated By:</strong> {report_data['requested_by']}<br/>
#             <strong>Date Generated:</strong> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
#         </div>
        
#         <h2>1. Executive Summary</h2>
#         <p>This report provides a comprehensive overview of the facility's Environmental, Social, and Governance (ESG) performance for the specified period. The primary focus of this assessment is on energy consumption, carbon footprint tracking, and HVAC operational efficiency.</p>
        
#         <h2>2. Key ESG Indicators Summary</h2>
#         <table>
#             <tr>
#                 <th>Metric</th>
#                 <th>Recorded Value</th>
#             </tr>
#             <tr>
#                 <td>Total Energy Consumed</td>
#                 <td>{report_data['total_energy_kwh']:,.2f} kWh</td>
#             </tr>
#             <tr>
#                 <td>Estimated Carbon Emissions</td>
#                 <td>{report_data['carbon_emissions_kg']:,.2f} kg CO2e</td>
#             </tr>
#             <tr>
#                 <td>HVAC Efficiency Rating</td>
#                 <td>{report_data['hvac_efficiency']}%</td>
#             </tr>
#             <tr>
#                 <td>Overall Sustainability Status</td>
#                 <td><strong>{report_data['sustainability_status']}</strong></td>
#             </tr>
#         </table>
        
#         <h2>3. Environmental Insights & Recommendations</h2>
#         <p>During the reporting period, the monitored facility consumed <strong>{report_data['total_energy_kwh']:,.2f} kWh</strong> of total energy. Based on regional grid emissions factors, this correlates to a carbon footprint of <strong>{report_data['carbon_emissions_kg']:,.2f} kg CO2e</strong>.</p>
        
#         <div class="insight-box">
#             <strong>HVAC Performance Insight:</strong><br/>
#             The HVAC systems operated at an average efficiency rating of {report_data['hvac_efficiency']}%. 
#             {
#                 "This indicates highly optimal performance. Continued preventative maintenance is advised to maintain these levels." 
#                 if report_data['hvac_efficiency'] >= 90 
#                 else "This indicates a decline in expected performance. Immediate optimization, filter replacement, or system auditing is recommended to reduce energy waste."
#             }
#         </div>
#     </body>
#     </html>
#     """

#     # 2. Convert HTML to PDF safely across Windows/Mac/Linux
#     temp_dir = tempfile.gettempdir()
#     pdf_path = os.path.join(temp_dir, f"{report_id}.pdf")
    
#     with open(pdf_path, "w+b") as result_file:
#         pisa_status = pisa.CreatePDF(html_content, dest=result_file)
        
#     if pisa_status.err:
#         raise Exception("xhtml2pdf failed to generate the PDF.")

#     # 3. Upload to Supabase Storage
#     supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
#     file_name = f"{report_id}.pdf"
#     bucket_name = "esg-reports" 

#     with open(pdf_path, 'rb') as f:
#         supabase.storage.from_(bucket_name).upload(
#             path=file_name,
#             file=f,
#             file_options={"content-type": "application/pdf"}
#         )

#     # 4. Get Public URL and clean up local file
#     public_url = supabase.storage.from_(bucket_name).get_public_url(file_name)
#     os.remove(pdf_path)
    
#     return public_url


# @tool(args_schema=GenerateReportInput)
# async def generate_esg_report_tool(start_date: str, end_date: str, total_energy_kwh: float, carbon_emissions_kg: float, hvac_efficiency: int, requested_by: str = "System Admin") -> str:
#     """
#     Creates an ESG report, generates a formatted PDF, uploads it to Supabase Storage, 
#     and saves the final record with the PDF link into the database.
#     """
#     try:
#         start_dt = datetime.fromisoformat(start_date.replace("Z", "+00:00"))
#         end_dt = datetime.fromisoformat(end_date.replace("Z", "+00:00"))
#     except ValueError:
#         return "ERROR: Invalid date format. Please use ISO 8601. DO NOT RETRY."

#     if not DATABASE_URL or not SUPABASE_URL:
#         return "CRITICAL ERROR: Database or Supabase URL is not configured. DO NOT RETRY."

#     try:
#         report_id = f"ESG-{datetime.now(timezone.utc).strftime('%Y%m')}-{str(uuid.uuid4())[:6].upper()}"
#         sustainability_status = "Optimal" if hvac_efficiency >= 90 else "Requires Optimization"
        
#         # 1. Generate PDF and Upload to Storage
#         report_data_for_pdf = {
#             "id": report_id,
#             "start_date": start_date,
#             "end_date": end_date,
#             "requested_by": requested_by,
#             "total_energy_kwh": total_energy_kwh,
#             "carbon_emissions_kg": carbon_emissions_kg,
#             "hvac_efficiency": hvac_efficiency,
#             "sustainability_status": sustainability_status
#         }
        
#         pdf_url = await asyncio.to_thread(generate_and_upload_pdf, report_data_for_pdf)

#         # 2. Save record to PostgreSQL database
#         conn = await asyncpg.connect(DATABASE_URL)
#         try:
#             query = """
#                 INSERT INTO esg_reports (
#                     id, period_start, period_end, generated_by, 
#                     total_energy_kwh, carbon_footprint_kg, 
#                     hvac_efficiency_rating, sustainability_status, report_pdf_url
#                 ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
#             """
#             await conn.execute(
#                 query,
#                 report_id,
#                 start_dt,
#                 end_dt,
#                 requested_by,
#                 total_energy_kwh,
#                 carbon_emissions_kg,
#                 hvac_efficiency,
#                 sustainability_status,
#                 pdf_url
#             )
#         finally:
#             await conn.close()
        
#         return json.dumps({
#             "status": "success",
#             "message": "Successfully generated ESG Report, created PDF, and saved to database.",
#             "report_id": report_id,
#             "pdf_download_url": pdf_url,
#             "summary": {
#                 "id": report_id,
#                 "period_start": start_date,
#                 "period_end": end_date,
#                 "generated_by": requested_by,
#                 "total_energy_kwh": total_energy_kwh,
#                 "carbon_footprint_kg": carbon_emissions_kg,
#                 "hvac_efficiency_rating": hvac_efficiency,
#                 "sustainability_status": sustainability_status,
#                 "report_pdf_url": pdf_url
#             }
#         })
        
#     except Exception as e:
#         return f"CRITICAL ERROR - Failed to generate ESG report: {str(e)}. DO NOT RETRY."
import json
import uuid
import os
import asyncio
import asyncpg
import tempfile
from datetime import datetime, timezone
from dotenv import load_dotenv, find_dotenv
from langchain_core.tools import tool
from pydantic import BaseModel, Field

# ReportLab imports for pure-Python PDF generation
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm

from supabase import create_client, Client

load_dotenv(find_dotenv())
DATABASE_URL = os.getenv("POSTGRES_URL")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY")

class GenerateReportInput(BaseModel):
    start_date: str = Field(..., description="The start date of the reporting period.")
    end_date: str = Field(..., description="The end date of the reporting period.")
    total_energy_kwh: float = Field(..., description="Total energy consumed in kWh.")
    carbon_emissions_kg: float = Field(..., description="Total estimated carbon emissions in kg.")
    hvac_efficiency: int = Field(..., description="The average HVAC system efficiency score.")
    requested_by: str = Field("System Admin", description="The admin user requesting the report.")


def generate_and_upload_pdf(report_data: dict) -> str:
    """
    Synchronous helper function to generate the PDF using reportlab 
    and upload it to Supabase.
    """
    report_id = report_data["id"]
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, f"{report_id}.pdf")
    
    # 1. Setup ReportLab Document
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=2*cm, 
        leftMargin=2*cm,
        topMargin=2*cm, 
        bottomMargin=2*cm
    )
    
    styles = getSampleStyleSheet()
    story = []

    # Custom Styles
    title_style = ParagraphStyle(
        name='TitleStyle',
        parent=styles['Heading1'],
        textColor=colors.HexColor('#2E7D32'),
        alignment=1, # Center
        spaceAfter=20
    )
    
    h2_style = ParagraphStyle(
        name='H2Style',
        parent=styles['Heading2'],
        textColor=colors.HexColor('#1565C0'),
        spaceBefore=15,
        spaceAfter=10,
        borderPadding=0
    )
    
    metadata_style = ParagraphStyle(
        name='Metadata',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#555555'),
        spaceAfter=20,
        leading=14
    )
    
    insight_style = ParagraphStyle(
        name='Insight',
        parent=styles['Normal'],
        backColor=colors.HexColor('#e3f2fd'),
        borderWidth=1,
        borderColor=colors.HexColor('#90caf9'),
        borderPadding=10,
        spaceBefore=15,
        leading=14
    )

    # 2. Build Document Content (Flowables)
    
    # Header
    story.append(Paragraph("Official ESG Performance Report", title_style))
    
    # Metadata
    metadata_text = f"""
    <b>Report ID:</b> {report_id}<br/>
    <b>Reporting Period:</b> {report_data['start_date']} to {report_data['end_date']}<br/>
    <b>Generated By:</b> {report_data['requested_by']}<br/>
    <b>Date Generated:</b> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC
    """
    story.append(Paragraph(metadata_text, metadata_style))
    
    # Executive Summary
    story.append(Paragraph("1. Executive Summary", h2_style))
    exec_summary = "This report provides a comprehensive overview of the facility's Environmental, Social, and Governance (ESG) performance for the specified period. The primary focus of this assessment is on energy consumption, carbon footprint tracking, and HVAC operational efficiency."
    story.append(Paragraph(exec_summary, styles['Normal']))
    
    # Key ESG Indicators Summary
    story.append(Paragraph("2. Key ESG Indicators Summary", h2_style))
    
    table_data = [
        ['Metric', 'Recorded Value'],
        ['Total Energy Consumed', f"{report_data['total_energy_kwh']:,.2f} kWh"],
        ['Estimated Carbon Emissions', f"{report_data['carbon_emissions_kg']:,.2f} kg CO2e"],
        ['HVAC Efficiency Rating', f"{report_data['hvac_efficiency']}%"],
        ['Overall Sustainability Status', report_data['sustainability_status']]
    ]
    
    # Table Styling
    esg_table = Table(table_data, colWidths=[10*cm, 6.5*cm])
    esg_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f0f4f8')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dddddd')),
        ('FONTNAME', (1, 4), (1, 4), 'Helvetica-Bold'), # Make status text bold
    ]))
    story.append(esg_table)
    
    # Environmental Insights
    story.append(Paragraph("3. Environmental Insights & Recommendations", h2_style))
    insights_text = f"During the reporting period, the monitored facility consumed <b>{report_data['total_energy_kwh']:,.2f} kWh</b> of total energy. Based on regional grid emissions factors, this correlates to a carbon footprint of <b>{report_data['carbon_emissions_kg']:,.2f} kg CO2e</b>."
    story.append(Paragraph(insights_text, styles['Normal']))
    
    # Dynamic Insight Box
    insight_msg = (
        "This indicates highly optimal performance. Continued preventative maintenance is advised to maintain these levels." 
        if report_data['hvac_efficiency'] >= 90 
        else "This indicates a decline in expected performance. Immediate optimization, filter replacement, or system auditing is recommended to reduce energy waste."
    )
    insight_box_text = f"<b>HVAC Performance Insight:</b><br/>The HVAC systems operated at an average efficiency rating of {report_data['hvac_efficiency']}%. {insight_msg}"
    story.append(Paragraph(insight_box_text, insight_style))
    
    # Build the PDF
    doc.build(story)

    # 3. Upload to Supabase Storage
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    file_name = f"{report_id}.pdf"
    bucket_name = "esg-reports" 

    with open(pdf_path, 'rb') as f:
        supabase.storage.from_(bucket_name).upload(
            path=file_name,
            file=f,
            file_options={"content-type": "application/pdf"}
        )

    # 4. Get Public URL and clean up local file
    public_url = supabase.storage.from_(bucket_name).get_public_url(file_name)
    os.remove(pdf_path)
    
    return public_url


@tool(args_schema=GenerateReportInput)
async def generate_esg_report_tool(start_date: str, end_date: str, total_energy_kwh: float, carbon_emissions_kg: float, hvac_efficiency: int, requested_by: str = "System Admin") -> str:
    """
    Creates an ESG report, generates a formatted PDF, uploads it to Supabase Storage, 
    and saves the final record with the PDF link into the database.
    """
    try:
        start_dt = datetime.fromisoformat(start_date.replace("Z", "+00:00"))
        end_dt = datetime.fromisoformat(end_date.replace("Z", "+00:00"))
    except ValueError:
        return "ERROR: Invalid date format. Please use ISO 8601. DO NOT RETRY."

    if not DATABASE_URL or not SUPABASE_URL:
        return "CRITICAL ERROR: Database or Supabase URL is not configured. DO NOT RETRY."

    try:
        report_id = f"ESG-{datetime.now(timezone.utc).strftime('%Y%m')}-{str(uuid.uuid4())[:6].upper()}"
        sustainability_status = "Optimal" if hvac_efficiency >= 90 else "Requires Optimization"
        
        # 1. Generate PDF and Upload to Storage
        report_data_for_pdf = {
            "id": report_id,
            "start_date": start_date,
            "end_date": end_date,
            "requested_by": requested_by,
            "total_energy_kwh": total_energy_kwh,
            "carbon_emissions_kg": carbon_emissions_kg,
            "hvac_efficiency": hvac_efficiency,
            "sustainability_status": sustainability_status
        }
        
        pdf_url = await asyncio.to_thread(generate_and_upload_pdf, report_data_for_pdf)

        # 2. Save record to PostgreSQL database
        conn = await asyncpg.connect(DATABASE_URL)
        try:
            query = """
                INSERT INTO esg_reports (
                    id, period_start, period_end, generated_by, 
                    total_energy_kwh, carbon_footprint_kg, 
                    hvac_efficiency_rating, sustainability_status, report_pdf_url
                ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
            """
            await conn.execute(
                query,
                report_id,
                start_dt,
                end_dt,
                requested_by,
                total_energy_kwh,
                carbon_emissions_kg,
                hvac_efficiency,
                sustainability_status,
                pdf_url
            )
        finally:
            await conn.close()
        
        return json.dumps({
            "status": "success",
            "message": "Successfully generated ESG Report, created PDF, and saved to database.",
            "report_id": report_id,
            "pdf_download_url": pdf_url,
            "summary": {
                "id": report_id,
                "period_start": start_date,
                "period_end": end_date,
                "generated_by": requested_by,
                "total_energy_kwh": total_energy_kwh,
                "carbon_footprint_kg": carbon_emissions_kg,
                "hvac_efficiency_rating": hvac_efficiency,
                "sustainability_status": sustainability_status,
                "report_pdf_url": pdf_url
            }
        })
        
    except Exception as e:
        return f"CRITICAL ERROR - Failed to generate ESG report: {str(e)}. DO NOT RETRY."
    
# ==============================================================================
# TEST BLOCK
# ==============================================================================
if __name__ == "__main__":
    from unittest.mock import patch, MagicMock, AsyncMock

    async def run_test():
        print("Starting isolated test for PDF generation...\n")
        
        # We temporarily mock the environment variables to bypass the connection checks
        global DATABASE_URL, SUPABASE_URL, SUPABASE_KEY
        original_db = DATABASE_URL
        original_sb_url = SUPABASE_URL
        original_sb_key = SUPABASE_KEY
        
        DATABASE_URL = "postgres://mock:mock@localhost:5432/mockdb"
        SUPABASE_URL = "https://mock.supabase.co"
        SUPABASE_KEY = "mock_key"

        # Mock the external connections (Supabase Upload & PostgreSQL Insert)
        # We also mock os.remove so the PDF doesn't delete, allowing us to inspect it!
        with patch('__main__.create_client') as mock_create_client, \
             patch('asyncpg.connect', new_callable=AsyncMock) as mock_pg_connect, \
             patch('os.remove') as mock_remove:
            
            # Setup fake Supabase bucket behavior
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase
            mock_bucket = mock_supabase.storage.from_.return_value
            mock_bucket.get_public_url.return_value = "https://mock.supabase.co/storage/v1/object/public/esg-reports/mock.pdf"
            
            # Setup fake Postgres behavior
            mock_conn = AsyncMock()
            mock_pg_connect.return_value = mock_conn

            # 1. Define sample arguments for our Langchain Tool
            test_inputs = {
                "start_date": "2023-10-01T00:00:00Z",
                "end_date": "2023-10-31T23:59:59Z",
                "total_energy_kwh": 45000.5,
                "carbon_emissions_kg": 12000.25,
                "hvac_efficiency": 95, 
                "requested_by": "Automated Testing Script"
            }

            # 2. Invoke the tool
            print("Invoking `generate_esg_report_tool` with dummy data...")
            result_json_str = await generate_esg_report_tool.ainvoke(test_inputs)
            
            # Catch plain text errors BEFORE parsing JSON
            if result_json_str.startswith("CRITICAL") or result_json_str.startswith("ERROR"):
                print(f"\n❌ [TEST FAILED] The tool encountered an internal error:\n\n{result_json_str}\n")
                return

            # 3. Parse and assert results
            result = json.loads(result_json_str)
            
            assert result["status"] == "success", f"Expected success status, got: {result.get('status')}"
            assert result["summary"]["sustainability_status"] == "Optimal", "Efficiency logic failed"
            
            print("\n✅ Test Passed: Tool execution succeeded and returned valid JSON.")
            print("\nTool Output:")
            print(json.dumps(result, indent=2))
            
            # Print the path so the user can go open the generated PDF
            if mock_remove.called:
                saved_pdf_path = mock_remove.call_args[0][0]
                print(f"\n📄 [SUCCESS] The generated PDF was saved and intentionally NOT deleted.")
                print(f"👉 You can view the file to check the ReportLab styling at: \n   {saved_pdf_path}\n")

        # Restore original environment variables
        DATABASE_URL = original_db
        SUPABASE_URL = original_sb_url
        SUPABASE_KEY = original_sb_key

    # Run the test
    asyncio.run(run_test())